#!/usr/bin/python3
"""
Also raise exceptions
"""


class ShortInputException(Exception):
	def __init__(self, length, atleast ):
		self.length = length
		self.atleast = atleast

try:
	text = input('Enter something: ')
	if len(text) < 3:
		raise ShortInputException
except KeyboardInterrupt:
	print('Program terminated')
except EOFError:
	print('Why did you call EOF on me?')
else:
	print(f'This is what you\'ve entered: {}')

